
export interface Currency {
  code: string;
  name: string;
}

// Comprehensive list of currencies. Note: frankfurter.app API only supports a subset.
// UI will allow selection, but conversion may fail for unsupported currencies.
// Sorted alphabetically by code.
export const currencies: Currency[] = [
    { code: "AED", name: "United Arab Emirates Dirham" },
    { code: "AFN", name: "Afghan Afghani" },
    { code: "ALL", name: "Albanian Lek" },
    { code: "AMD", name: "Armenian Dram" },
    { code: "ANG", name: "Netherlands Antillean Guilder" },
    { code: "AOA", name: "Angolan Kwanza" },
    { code: "ARS", name: "Argentine Peso" },
    { code: "AUD", name: "Australian Dollar" },
    { code: "AWG", name: "Aruban Florin" },
    { code: "AZN", name: "Azerbaijani Manat" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
    { code: "BBD", name: "Barbadian Dollar" },
    { code: "BDT", name: "Bangladeshi Taka" },
    { code: "BGN", name: "Bulgarian Lev" },
    { code: "BHD", name: "Bahraini Dinar" },
    { code: "BIF", name: "Burundian Franc" },
    { code: "BMD", name: "Bermudan Dollar" },
    { code: "BND", name: "Brunei Dollar" },
    { code: "BOB", name: "Bolivian Boliviano" },
    { code: "BRL", name: "Brazilian Real" },
    { code: "BSD", name: "Bahamian Dollar" },
    { code: "BTN", name: "Bhutanese Ngultrum" },
    { code: "BWP", name: "Botswanan Pula" },
    { code: "BYN", name: "Belarusian Ruble" },
    { code: "BZD", name: "Belize Dollar" },
    { code: "CAD", name: "Canadian Dollar" },
    { code: "CDF", name: "Congolese Franc" },
    { code: "CHF", name: "Swiss Franc" },
    { code: "CLP", name: "Chilean Peso" },
    { code: "CNY", name: "Chinese Yuan" },
    { code: "COP", name: "Colombian Peso" },
    { code: "CRC", name: "Costa Rican Colón" },
    { code: "CUP", name: "Cuban Peso" },
    { code: "CVE", name: "Cape Verdean Escudo" },
    { code: "CZK", name: "Czech Koruna" },
    { code: "DJF", name: "Djiboutian Franc" },
    { code: "DKK", name: "Danish Krone" },
    { code: "DOP", name: "Dominican Peso" },
    { code: "DZD", name: "Algerian Dinar" },
    { code: "EGP", name: "Egyptian Pound" },
    { code: "ERN", name: "Eritrean Nakfa" },
    { code: "ETB", name: "Ethiopian Birr" },
    { code: "EUR", name: "Euro" },
    { code: "FJD", name: "Fijian Dollar" },
    { code: "FKP", name: "Falkland Islands Pound" },
    { code: "FOK", name: "Faroese Króna" },
    { code: "GBP", name: "British Pound Sterling" },
    { code: "GEL", name: "Georgian Lari" },
    { code: "GGP", name: "Guernsey Pound" },
    { code: "GHS", name: "Ghanaian Cedi" },
    { code: "GIP", name: "Gibraltar Pound" },
    { code: "GMD", name: "Gambian Dalasi" },
    { code: "GNF", name: "Guinean Franc" },
    { code: "GTQ", name: "Guatemalan Quetzal" },
    { code: "GYD", name: "Guyanaese Dollar" },
    { code: "HKD", name: "Hong Kong Dollar" },
    { code: "HNL", name: "Honduran Lempira" },
    { code: "HRK", name: "Croatian Kuna" },
    { code: "HTG", name: "Haitian Gourde" },
    { code: "HUF", name: "Hungarian Forint" },
    { code: "IDR", name: "Indonesian Rupiah" },
    { code: "ILS", name: "Israeli New Shekel" },
    { code: "IMP", name: "Isle of Man Pound" },
    { code: "INR", name: "Indian Rupee" },
    { code: "IQD", name: "Iraqi Dinar" },
    { code: "IRR", name: "Iranian Rial" },
    { code: "ISK", name: "Icelandic Króna" },
    { code: "JEP", name: "Jersey Pound" },
    { code: "JMD", name: "Jamaican Dollar" },
    { code: "JOD", name: "Jordanian Dinar" },
    { code: "JPY", name: "Japanese Yen" },
    { code: "KES", name: "Kenyan Shilling" },
    { code: "KGS", name: "Kyrgystani Som" },
    { code: "KHR", name: "Cambodian Riel" },
    { code: "KID", name: "Kiribati Dollar" },
    { code: "KMF", name: "Comorian Franc" },
    { code: "KRW", name: "South Korean Won" },
    { code: "KWD", name: "Kuwaiti Dinar" },
    { code: "KYD", name: "Cayman Islands Dollar" },
    { code: "KZT", name: "Kazakhstani Tenge" },
    { code: "LAK", name: "Laotian Kip" },
    { code: "LBP", name: "Lebanese Pound" },
    { code: "LKR", name: "Sri Lankan Rupee" },
    { code: "LRD", name: "Liberian Dollar" },
    { code: "LSL", name: "Lesotho Loti" },
    { code: "LYD", name: "Libyan Dinar" },
    { code: "MAD", name: "Moroccan Dirham" },
    { code: "MDL", name: "Moldovan Leu" },
    { code: "MGA", name: "Malagasy Ariary" },
    { code: "MKD", name: "Macedonian Denar" },
    { code: "MMK", name: "Myanma Kyat" },
    { code: "MNT", name: "Mongolian Tugrik" },
    { code: "MOP", name: "Macanese Pataca" },
    { code: "MRU", name: "Mauritanian Ouguiya" },
    { code: "MUR", name: "Mauritian Rupee" },
    { code: "MVR", name: "Maldivian Rufiyaa" },
    { code: "MWK", name: "Malawian Kwacha" },
    { code: "MXN", name: "Mexican Peso" },
    { code: "MYR", name: "Malaysian Ringgit" },
    { code: "MZN", name: "Mozambican Metical" },
    { code: "NAD", name: "Namibian Dollar" },
    { code: "NGN", name: "Nigerian Naira" },
    { code: "NIO", name: "Nicaraguan Córdoba" },
    { code: "NOK", name: "Norwegian Krone" },
    { code: "NPR", name: "Nepalese Rupee" },
    { code: "NZD", name: "New Zealand Dollar" },
    { code: "OMR", name: "Omani Rial" },
    { code: "PAB", name: "Panamanian Balboa" },
    { code: "PEN", name: "Peruvian Nuevo Sol" },
    { code: "PGK", name: "Papua New Guinean Kina" },
    { code: "PHP", name: "Philippine Peso" },
    { code: "PKR", name: "Pakistani Rupee" },
    { code: "PLN", name: "Polish Zloty" },
    { code: "PYG", name: "Paraguayan Guarani" },
    { code: "QAR", name: "Qatari Rial" },
    { code: "RON", name: "Romanian Leu" },
    { code: "RSD", name: "Serbian Dinar" },
    { code: "RUB", name: "Russian Ruble" },
    { code: "RWF", name: "Rwandan Franc" },
    { code: "SAR", name: "Saudi Riyal" },
    { code: "SBD", name: "Solomon Islands Dollar" },
    { code: "SCR", name: "Seychellois Rupee" },
    { code: "SDG", name: "Sudanese Pound" },
    { code: "SEK", name: "Swedish Krona" },
    { code: "SGD", name: "Singapore Dollar" },
    { code: "SHP", name: "Saint Helena Pound" },
    { code: "SLE", name: "Sierra Leonean Leone" },
    { code: "SLL", name: "Sierra Leonean Leone (Old)" },
    { code: "SOS", name: "Somali Shilling" },
    { code: "SRD", name: "Surinamese Dollar" },
    { code: "SSP", name: "South Sudanese Pound" },
    { code: "STN", name: "São Tomé and Príncipe Dobra" },
    { code: "SYP", name: "Syrian Pound" },
    { code: "SZL", name: "Swazi Lilangeni" },
    { code: "THB", name: "Thai Baht" },
    { code: "TJS", name: "Tajikistani Somoni" },
    { code: "TMT", name: "Turkmenistani Manat" },
    { code: "TND", name: "Tunisian Dinar" },
    { code: "TOP", name: "Tongan Paʻanga" },
    { code: "TRY", name: "Turkish Lira" },
    { code: "TTD", name: "Trinidad and Tobago Dollar" },
    { code: "TVD", name: "Tuvaluan Dollar" },
    { code: "TWD", name: "New Taiwan Dollar" },
    { code: "TZS", name: "Tanzanian Shilling" },
    { code: "UAH", name: "Ukrainian Hryvnia" },
    { code: "UGX", name: "Ugandan Shilling" },
    { code: "USD", name: "United States Dollar" },
    { code: "UYU", name: "Uruguayan Peso" },
    { code: "UZS", name: "Uzbekistan Som" },
    { code: "VES", name: "Venezuelan Bolívar Soberano" },
    { code: "VND", name: "Vietnamese Dong" },
    { code: "VUV", name: "Vanuatu Vatu" },
    { code: "WST", name: "Samoan Tala" },
    { code: "XAF", name: "CFA Franc BEAC" },
    { code: "XCD", name: "East Caribbean Dollar" },
    //{ code: "XCG", name: "XCG" }, // Placeholder? Removed
    { code: "XDR", name: "Special Drawing Rights" },
    { code: "XOF", name: "CFA Franc BCEAO" },
    { code: "XPF", name: "CFP Franc" },
    { code: "YER", name: "Yemeni Rial" },
    { code: "ZAR", name: "South African Rand" },
    { code: "ZMW", name: "Zambian Kwacha" },
    { code: "ZWL", name: "Zimbabwean Dollar" },
];


// Filtered list based on known frankfurter.app support (for reference or future use)
export const frankfurterSupportedCurrencies: Currency[] = [
  { code: "AUD", name: "Australian Dollar" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DKK", name: "Danish Krone" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound Sterling" },
  { code: "HKD", name: "Hong Kong Dollar" },
  // { code: "HRK", name: "Croatian Kuna" }, // Often phased out
  { code: "HUF", name: "Hungarian Forint" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "INR", name: "Indian Rupee" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "KRW", name: "South Korean Won" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "THB", name: "Thai Baht" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "USD", name: "United States Dollar" },
  { code: "ZAR", name: "South African Rand" },
  // Note: PKR is NOT supported by frankfurter.app
];


// Static conversion rates relative to USD (Base: USD = 1)
// Source: Example data, should be updated periodically or replaced with a live API
export const conversion_rates: { [key: string]: number } = {
  "USD": 1,
  "AED": 3.6725,
  "AFN": 71.1687,
  "ALL": 86.8936,
  "AMD": 390.5927,
  "ANG": 1.7900,
  "AOA": 917.9414,
  "ARS": 1174.1700,
  "AUD": 1.5653,
  "AWG": 1.7900,
  "AZN": 1.6993,
  "BAM": 1.7216,
  "BBD": 2.0000,
  "BDT": 121.4694,
  "BGN": 1.7216,
  "BHD": 0.3760,
  "BIF": 2968.8005,
  "BMD": 1.0000,
  "BND": 1.3147,
  "BOB": 6.9189,
  "BRL": 5.6862,
  "BSD": 1.0000,
  "BTN": 85.4740,
  "BWP": 13.7887,
  "BYN": 3.0756,
  "BZD": 2.0000,
  "CAD": 1.3862,
  "CDF": 2892.2818,
  "CHF": 0.8281,
  "CLP": 935.3539,
  "CNY": 7.2902,
  "COP": 4233.7562,
  "CRC": 504.9424,
  "CUP": 24.0000,
  "CVE": 97.0618,
  "CZK": 21.9777,
  "DJF": 177.7210,
  "DKK": 6.5707,
  "DOP": 59.2244,
  "DZD": 132.3155,
  "EGP": 50.9189,
  "ERN": 15.0000,
  "ETB": 132.8100,
  "EUR": 0.8803,
  "FJD": 2.2527,
  "FKP": 0.7516,
  "FOK": 6.5702,
  "GBP": 0.7516,
  "GEL": 2.7475,
  "GGP": 0.7516,
  "GHS": 14.7009,
  "GIP": 0.7516,
  "GMD": 72.6577,
  "GNF": 8719.8380,
  "GTQ": 7.6973,
  "GYD": 209.0963,
  "HKD": 7.7574,
  "HNL": 25.9119,
  "HRK": 6.6323,
  "HTG": 130.6969,
  "HUF": 357.6055,
  "IDR": 16837.1183,
  "ILS": 3.6283,
  "IMP": 0.7516,
  "INR": 85.4741,
  "IQD": 1309.0725,
  "IRR": 41874.6918,
  "ISK": 127.7460,
  "JEP": 0.7516,
  "JMD": 158.4778,
  "JOD": 0.7090,
  "JPY": 143.6909,
  "KES": 129.2650,
  "KGS": 86.6235,
  "KHR": 3983.8974,
  "KID": 1.5651,
  "KMF": 433.0590,
  "KRW": 1438.3737,
  "KWD": 0.3064,
  "KYD": 0.8333,
  "KZT": 514.1750,
  "LAK": 21737.6797,
  "LBP": 89500.0000,
  "LKR": 299.3322,
  "LRD": 199.9741,
  "LSL": 18.7150,
  "LYD": 5.4594,
  "MAD": 9.2592,
  "MDL": 17.2285,
  "MGA": 4509.0371,
  "MKD": 54.1171,
  "MMK": 2097.8589,
  "MNT": 3591.8736,
  "MOP": 7.9901,
  "MRU": 39.6925,
  "MUR": 45.2162,
  "MVR": 15.4196,
  "MWK": 1733.7017,
  "MXN": 19.5309,
  "MYR": 4.3741,
  "MZN": 63.6624,
  "NAD": 18.7150,
  "NGN": 1605.1204,
  "NIO": 36.7744,
  "NOK": 10.4319,
  "NPR": 136.7584,
  "NZD": 1.6797,
  "OMR": 0.3845,
  "PAB": 1.0000,
  "PEN": 3.6840,
  "PGK": 4.0792,
  "PHP": 56.2404,
  "PKR": 281.1078,
  "PLN": 3.7610,
  "PYG": 8028.9366,
  "QAR": 3.6400,
  "RON": 4.3808,
  "RSD": 103.1528,
  "RUB": 82.6214,
  "RWF": 1424.8411,
  "SAR": 3.7500,
  "SBD": 8.5083,
  "SCR": 14.3046,
  "SDG": 484.9103,
  "SEK": 9.6965,
  "SGD": 1.3145,
  "SHP": 0.7516,
  "SLE": 22.6844,
  "SLL": 22684.4001,
  "SOS": 571.4279,
  "SRD": 36.6779,
  "SSP": 4514.3095,
  "STN": 21.5663,
  "SYP": 12887.7408,
  "SZL": 18.7150,
  "THB": 33.5294,
  "TJS": 10.6935,
  "TMT": 3.4958,
  "TND": 2.9891,
  "TOP": 2.3737,
  "TRY": 38.4272,
  "TTD": 6.7792,
  "TVD": 1.5651,
  "TWD": 32.4761,
  "TZS": 2683.0108,
  "UAH": 41.8000,
  "UGX": 3651.0934,
  "UYU": 41.9523,
  "UZS": 12916.4637,
  "VES": 86.1143,
  "VND": 26018.9085,
  "VUV": 120.0380,
  "WST": 2.7575,
  "XAF": 577.4120,
  "XCD": 2.7000,
  "XDR": 0.7385,
  "XOF": 577.4120,
  "XPF": 105.0431,
  "YER": 244.9294,
  "ZAR": 18.7195,
  "ZMW": 28.0633,
  "ZWL": 26.8038
};
